alias startpostgres="sudo service postgresql start"
alias stoppostgres="sudo service postgresql stop"
alias gst="git status"
alias gcmsg="git commit -m"
alias gaa="git add ."
alias gp="git push"
alias gl="git pull"
