tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "autoconf"
brew "automake"
brew "berglas"
brew "coreutils"
brew "cowsay"
brew "figlet"
brew "fortune"
brew "git"
brew "openssl@1.1"
brew "readline"
brew "sqlite"
brew "glib"
brew "libtool"
brew "pkg-config"
brew "libksba"
brew "gnupg"
brew "htop"
brew "imagemagick"
brew "jq"
brew "libyaml"
brew "mas"
brew "neofetch"
brew "node"
brew "postgresql@9.6", restart_service: true, link: true
brew "redis", restart_service: true
brew "sl"
brew "speedtest-cli"
brew "tmux"
brew "tree"
brew "watchman"
brew "yarn"
brew "zlib"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
cask "brave-browser"
cask "discord"
cask "google-cloud-sdk"
cask "graphiql"
cask "hyper"
cask "lastpass"
cask "macs-fan-control"
cask "microsoft-teams"
cask "mono-mdk-for-visual-studio"
cask "ngrok"
cask "nordvpn"
cask "obsidian"
cask "onedrive"
cask "postman"
cask "slack"
cask "tower"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Xcode", id: 497799835
